### ISSUE TITLE
TypeError when establishing connection to messaging service after prolonged disconnect

### ISSUE THREAD

**Issue by grs** [EnMasseProject/routilities#28]
If the console is unable to connect to a router for some time, when it does finally reconnect it can result in an exception like the following:

Unhandled rejection TypeError: Cannot read property 'length' of undefined
    at same_list (/opt/app-root/src/lib/router_stats.js:154:23)
    at same_routers (/opt/app-root/src/lib/router_stats.js:165:12)
    at /opt/app-root/src/lib/router_stats.js:171:14
    at tryCatcher (/opt/app-root/src/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/opt/app-root/src/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/opt/app-root/src/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/opt/app-root/src/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/opt/app-root/src/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/opt/app-root/src/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/opt/app-root/src/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/opt/app-root/src/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

**Comment by ppatierno** [comment]
@grs does it fix the problem I had with the need to restart the admin pod ? If yes, @lulf can we tag a new 0.11.2 version with this fix ?

**Comment by grs** [comment]
Yes, I believe it does.
